### ISSUE TITLE
Why was the min android version changed from 6 to 9?

### ISSUE THREAD

**Issue by parth-koshta** [star-micronics/react-native-star-io10#104]
## Description
In the latest update of this library the minimum android version was changed from 6 to 9. 
Can we know the need of doing it? We are using this library in our app and we have a good chunk of users below Android 9 and it wouldn't be possible for us to end support for those users.

## Your device where the bug occurs 
 - Device: 
    *All android devices below Android 9*
 - OS:
    *Android*
 - Version
    *1.4.0*

## Your printer
- Model Names:
    *TSP 100*

**Comment by shardul111** [comment]
@bandit-ibayashi Can you please help with the above query ?

**Comment by zacdemi** [comment]
We also have the same question. Thanks

**Comment by bandit-ibayashi** [comment]
@parth-koshta @shardul111 @zacdemi 
We define the supported OS version and raise it as necessary, taking into account the number of years since that version was released, the market share rate, and the life cycle of the device.

Of course, we fully understand that there are users who use versions earlier than Android 9. However, we also need to focus our limited resources on what we need to do to continue to provide solutions, such as supporting an Android SDK version that is raised every year ([ref](https://developer.android.com/google/play/requirements/target-sdk)), and we will periodically raise the supported OS version.
Support here means that the version is being evaluated on that Android OS. The current version of StarIO10 v1.5.0 can be specified as `minSdkVersion 23`. (Please verify thoroughly that it works).

We much appreciate your understanding.
