### ISSUE TITLE
StarSpoolJobSettings not working on TSP650ii

### ISSUE THREAD

**Issue by manage-some** [star-micronics/react-native-star-io10#109]
I have a star tsp650ii printer and it works fine for regular printing jobs using this library. However I need it enable spooler settings in order to printer continues print jobs without missing any print, but I'm having an error when trying to print with spooler settings.

This is my printer settings
![WhatsApp Image 2024-01-19 at 6 31 20 AM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/1eed5689-facb-4077-bd7b-afb14955be64)
![WhatsApp Image 2024-01-19 at 6 31 21 AM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/f53cf164-1e09-4f53-8f3b-f21f7c3f3010)

This is the error I'm getting
<img width="591" alt="Screenshot 2024-01-19 at 6 35 29 AM" src="https://github.com/star-micronics/react-native-star-io10/assets/113262320/3f6b4193-e3db-48f6-a968-9c727359c2c3">

For Reference, this is the settings on the chip at the back of my printer
![WhatsApp Image 2024-01-19 at 6 40 17 AM](https://github.com/star-micronics/react-native-star-io10/assets/113262320/033260e7-2f3b-455d-90e9-ae66a6c1873f)

I'm using the code from the example folder here
<img width="873" alt="Screenshot 2024-01-19 at 6 36 20 AM" src="https://github.com/star-micronics/react-native-star-io10/assets/113262320/1e3ab86d-91f0-4c59-a416-f17aeee5ca5a">

**Comment by manage-some** [comment]
@bandit-ibayashi this class is only available for two models.
We're trying to integrate star printer sdk for RN in our [POS app](https://www.eposmatic.com/) which needs to sends regular/simultaneous/overlapping print jobs. We require a queue mechanism so no print misses out. 
Is there any other way we could achieve the objective if **SarSpoolJobSetting** class is not supported in majority of models?

Objectives:
1 - Implement Queue mechanism to support multiple print jobs simultaneously
2 - Automatic reprinting (Retry on fail)


The sdk is useless in a practical manner if it does not support the above mentioned points for the majority of the models

**Comment by manage-some** [comment]
@bandit-ibayashi sir any guidance on how we can print multiple jobs in a queue for **tsp650II** and **tsp100IIILAN**

**Comment by bandit-ibayashi** [comment]
@manage-some I'm afraid the late response.
It prevents lost print data by holding print data until printing is successfully completed on the host device side and processing errors appropriately.

When printing from multiple host devices to one Ethernet-connected TSP650II, wait until printing from the other device is completed.
From your Self-Printing information, TCP#9100 Multi-Session is disabled, so a host device will occupy the communication from [`StarPrinter.open()`](https://www.star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-printer/open.html#star-printer-open) to [`StarPrinter.close()`](https://www.star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-printer/close.html#star-printer-close) of one host terminal. If another host terminal executes `StarPrinter.open()` , `StarIO10InUseError` will be returned. Therefore, waiting for a bit in case of an `StarIO10InUseError` and then resending the data will allow it to be printed.

When printing from one host device to one TSP650II, a mechanism for holding print data in the application can be implemented so that the next data is printed after one data has been successfully printed, which will ensure reliable printing.

If my understanding is different, please let me know.

Thanks.
