### ISSUE TITLE
New Arch Support

### ISSUE THREAD

**Issue by manage-some** [star-micronics/react-native-star-io10#122]
We've release a new update on playstore that uses New Arch of React Native. However on old android devices, we have been reported that the app breaks. Upon investigation, we found out that it's because of this library specially in the case when app is connected to 3-4 printers and queue stacks up. When we disable New Arch, it seems to work fine on old android devices as well.

**Comment by bandit-ibayashi** [comment]
@manage-some Thank you for your report.

Could you please fill in the template that appears when you post this Issue so that we can get a clearer understanding of the situation?
Please let us know your environment and the crashes you are seeing at the time so we can better understand this issue.

Thank you in advance.

----
## Description
A clear and concise description of what a bug is.

## Your device where the bug occurs 
 - Device: 
    *e.g. iPhone 13*
 - OS:
    *e.g. iOS 15.0*
 - Browser: 
    *e.g. Safari*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. mC-Print3*
- Firmware Version:
    *e.g. 3.5*
- Interface:
    *e.g. Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

Also, the result of executing the command `npx react-native info`.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Add any other context about the bug here.

**Comment by bandit-ibayashi** [comment]
This Issue is closed because there has been no movement for over 3 months. If you continue to experience problems, please let us know.

**Comment by can-miki** [comment]
I noticed that a related issue has been posted, and I have already provided an answer there. Please take a look.
https://github.com/star-micronics/react-native-star-io10/issues/146

If you encounter any issues, please open a new issue. Thank you for your cooperation.
