### ISSUE TITLE
Unable to Discover TSP100IIILAN with LAN, Bluetooth, or USB using react-native-star-io10

### ISSUE THREAD

**Issue by narthanan24** [star-micronics/react-native-star-io10#133]
## Description

I am unable to discover the **TSP100IIILAN**(printerfront: Star TSP100III futurePRINT / back: MODEL TSP100   TSP143IIILAN) printer using the `react-native-star-io10` library through LAN, Bluetooth, or USB. Additionally, I tried the **Star Quick Setup Utility** app, which also failed to find the printer. However, the printer's IP address responds to pings, indicating it is connected to the network.

## Environment:
- **Printer Model:** TSP100IIILAN
- **Connection Methods Tested:** LAN (Ethernet), Bluetooth, USB
- **Discovery Library:** `react-native-star-io10`
- **Operating System:** (e.g., Windows/Linux/macOS)
- **Network Configuration:**
  - Printer IP: 192.168.2.141
  - Ping Response: Successful (see below)

## Ping Test Results:

ping 192.168.2.141

Pinging 192.168.2.141 with 32 bytes of data:
Reply from 192.168.2.141: bytes=32 time=121ms TTL=64
Reply from 192.168.2.141: bytes=32 time<1ms TTL=64
Reply from 192.168.2.141: bytes=32 time<1ms TTL=64
Reply from 192.168.2.141: bytes=32 time=15ms TTL=64

Ping statistics for 192.168.2.141:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 121ms, Average = 34ms

## Steps to Reproduce:
1. Connect the TSP100IIILAN printer to the network via LAN (IP: 192.168.2.141).
2. Use the discovery function in the `react-native-star-io10` library for LAN, Bluetooth, or USB.
3. Verify the printer is not discovered in any mode.
4. Attempt to discover the printer using the **Star Quick Setup Utility** (fails as well).
5. Ping the printer IP address to confirm network connectivity (successful).

## Expected Behavior:
- The `react-native-star-io10` library should successfully discover the printer over LAN, Bluetooth, or USB.

## Actual Behavior:
- The `react-native-star-io10` library fails to discover the printer.
- The **Star Quick Setup Utility** app also fails to discover the printer.

## Additional Information:
- The printer's IP address responds to pings, indicating it is connected to the network.
- All cables, network configuration, and firewall settings have been verified.
- Other devices on the same network are discoverable using similar methods.

Please let me know if additional details or logs are required.

**Comment by can-miki** [comment]
Thank you for your inquiry.

Based on the information you provided, I conducted a confirmation. I confirmed that the TSP100III LAN printer can be discovered without any issues using the Star Quick Setup Utility (iOS and Android).
The Star Quick Setup Utility internally uses the starIO10 library.
Since the printer can be discovered in our lab environment, the issue may be caused by a network or environmental factor.
Therefore, we would like to request additional information about your current situation. Could you please provide the following details?

1. About the device and OS you are using:
Are you using iOS or Android?

2. About your network environment:
Is there any factor in your network that could be causing an obstacle (e.g., specific firewall settings or network restrictions)?

3. Background information:
Was this issue occurring with a printer that had previously been connected successfully, or was this your first attempt at connecting the printer?
Have there been any recent changes to your library, device, or network configuration?

4. Bug report:
For reference, could you please provide the information we require in our bug report template?
Also, we would like to know the information about `react-native info`.

If there are any changes or potential factors in your environment or situation, we would appreciate it if you could share those with us. Based on the provided information, we believe we will be able to proceed with further investigation.

Thank you very much for your cooperation.

**Comment by can-miki** [comment]
Regarding point 2, please make sure that the printer and the host terminal are on the same network (segment). If they are on different segments of the same network, it may not work.
Do you have any information regarding network configuration?

**Comment by narthanan24** [comment]
Thank you for your response and detailed guidance.

You are correct; this appears to be a network segment issue. Upon reviewing the network configuration, the printer and the host terminal are on different network segments, which explains the discovery failure. I'll work on reconfiguring the network to ensure both devices are on the same segment and will test the discovery functionality again.
