### ISSUE TITLE
Receipt content is blurry on SP700

### ISSUE THREAD

**Issue by nguyen-vo** [star-micronics/react-native-star-io10#17]
Hi, one of our clients reported to us that their receipt content is blurry. It only occurs to our app since their printer works fine on Clover system. 
![image](https://user-images.githubusercontent.com/65175891/124141075-125c9780-da57-11eb-87bd-899cd9d9dbe6.jpeg)

**Comment by gare-bear** [comment]
@nguyen-vo looks to me like it might be time to replace the ink ribbon. 
Do you know when the last time it was changed?

**Comment by nguyen-vo** [comment]
@gare-bear Hi thanks for replying. I don't know when the ink ribbon was replaced. But from what my client described, the print works just fine with other system

**Comment by gare-bear** [comment]
@nguyen-vo how are you generating the receipt? is the job a bitmap or plain text?
can you show a comparison between the two?

**Comment by nguyen-vo** [comment]
first I generate the text and then pass it in the command method. I attach my code below
![Screen Shot 2021-07-16 at 2 22 34 PM](https://user-images.githubusercontent.com/65175891/125992517-ce1d3af4-4c40-45fe-bac5-99dc8778895c.png)

**Comment by gare-bear** [comment]
@nguyen-vo thanks for sharing your code. You're printing text which is the preferred approach for our Dot Matrix printers since they have a lower DPI compared to our Thermals. 

I'd suggest adding [styleBold](https://www.star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/style-bold.html) to your PrinterBuilder, see if that changes the end result.

I'd need a copy of of the other receipt for comparison but I honestly think changing the ribbon will fix the issue.

**Comment by nguyen-vo** [comment]
@gare-bear thanks for your assist:D. I will try that
