### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by Gondolav** [star-micronics/react-native-star-io10#18]
Hi, does it work with [Expo](https://expo.io)? @bandit-ibayashi

**Comment by Adrianotiger** [comment]
Maybe it need to be listed in:

https://reactnative.directory/

Expo can find it on Android, but I am not able to use it. I get an error:

Error: "null is not an object (evaluating 'o.NativeModules.StarDeviceDiscoveryManagerWrapper.init')" in  << l <<  << l

**Comment by gare-bear** [comment]
@Gondolav although we would love to provide Expo support, it is not possible to include custom modules when using the Expo CLI/Expo client app. The React Native [documentation](https://reactnative.dev/docs/environment-setup) is very clear on this.

"Because you don't build any native code when using Expo to create a project, it's not possible to include custom native modules beyond the React Native APIs and components that are available in the Expo client app."

We'll add this to the Wiki for this repo in the near future. It should help others with the same question.
