### ISSUE TITLE
Example project does not work with XCode 12.5.1

### ISSUE THREAD

**Issue by joarwilk** [star-micronics/react-native-star-io10#22]
```
DistributedMutex-inl.h:1051:5: 'atomic_notify_one<unsigned long>' is unavailable


node_modules/react-native-star-io10/example/ios/Pods/Headers/Private/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h:1051:5: 'atomic_notify_one<unsigned long>' is unavailable
```

This is completely fresh and untouched. I just started the example project and tried to make a release build.

**Comment by gare-bear** [comment]
@joarwilk This issue seems to be with Flipper, the debugging tool for RN.
I think this has already been fixed but our podfile hasn't been updated.

In the podfile, change line 20 to:
`use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', , 'Flipper-RSocket' => '1.3.1' })`

Here's the relevant GitHub issue from [Flipper](https://github.com/facebook/flipper/issues/2215) and the [fix](https://github.com/facebook/flipper/issues/2215#issuecomment-829102757).

**Comment by joarwilk** [comment]
Works after the recent commit/change
