### ISSUE TITLE
[Android] `StarPrinterInformation` object returns `emulation: unknown` to all BT printers

### ISSUE THREAD

**Issue by yongmin86k** [star-micronics/react-native-star-io10#32]
Hi, 

There is an issue of `StarPrinterInformation` object returns `emulation: unknown` to all BT printers on Android

Using `StarDeviceDiscoveryManager.startDiscovery()` 
and `StarDeviceDiscoveryManager.onPrinterFound: (printer: StarPrinter) => void`, 
`StarPrinter.information`  is not working as expected

To enable, `print()` method, `emulation` property should be stored and returned, but it doesn't show up for all Star Bluetooth printers.

I've checked LAN/WiFi printers, they work fine.

Is there a workaround to get the `emulation` value?

![image](https://user-images.githubusercontent.com/20639360/140255911-0e163890-3a0d-4197-82ab-b7c7b2148866.png)

**Comment by gare-bear** [comment]
@yongmin86k looks like this is the same as #30.

@bandit-ibayashi if we can't get a usable PrinterInformation object for BT printers, how do you propose we can work around this?

**Comment by yongmin86k** [comment]
@gare-bear 

Hello 😁, (didn't expect to see you here again)

My previous option was using the other StarPrinter package, [react-native-star-prnt](https://github.com/infoxicator/react-native-star-prnt)

It returns the name of a model
![image](https://user-images.githubusercontent.com/20639360/140263100-bf2135c9-b93b-4a5a-bea9-9b6ecade3a09.png)

**Comment by gare-bear** [comment]
@yongmin86k We're going to add better model detection in a future update. For Bluetooth printers that include the model in the Bluetooth Device Name (e.g. mC-Print3-J0164), we'll properly detect it as mC-Print3. In order for this solution to work, its important that you don't change the printers Bluetooth Device Name.

This will give us coverage to detect the model for most Bluetooth printers, but not all due to hardware limitations. Once we can detect the model name properly, then the printers emulation will be reported as well.

**Comment by bandit-ibayashi** [comment]
We updated the specification that the printer model can be estimated and acquired for some printers with Bluetooth device name set to the initial value (TSP100IIIBI, mPOP, mC-Print2/3 and SM-L200/L300) when using `StarDeviceDiscoveryManager` class.

As @gare-bear said, there are some restrictions to using this feature.
* Bluetooth Device Name needs to be kept as the default.
* This function is available on TSP100IIIBI, mPOP, mC-Print2/3 and SM-L200/L300.
