### ISSUE TITLE
what is alert native  .actionPrintText is not available for tsp100iiibi

### ISSUE THREAD

**Issue by AbdullahIqbal** [star-micronics/react-native-star-io10#55]
HI 
if some tag is not available for some model what is the alternative for that Like
 .actionPrintText is not available for tsp100iiibi

**Comment by bandit-ibayashi** [comment]
Hi, @AbdullahIqbal 

Due to differences in printer capabilities, not all `PrinterBuilder` methods are available on every device.
In particular, TSP100III series does not have built-in font data, so it is limited to printing graphically, and it does not support the `actionPrintText()` method.

If you want to print receipt data on the TSP100IIIIBI, an alternative would be to create the receipt as an image and print it using [actionPrintImage](https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/action-print-image.html#star-xpand-command-printer-builder-action-print-image) method. 

It is discussed in Issue #10 how to create receipt images in React Native.

Thanks.

**Comment by AbdullahIqbal** [comment]
HI
Thanks for the guide. so what is the way to set the height of the image in
actionPrintImage
<https://star-m.jp/products/s_print/sdk/react-native-star-io10/manual/en/api-reference/star-xpand-command/printer-builder/action-print-image.html#star-xpand-command-printer-builder-action-print-image>
